[homie]
# The prefix to use to generate Homie device IDs.
device_id_prefix="cloudbbq"
# The Homie base MQTT topic.
prefix="homie"

[mqtt]
# The hostname of the MQTT broker to use.
host="test.mosquitto.org"
# The port number of the MQTT broker to use.
port=1883
# The prefix to use to generate client names for connecting to the MQTT broker.
client_prefix="cloudbbq"
# The username with which to authenticate to the MQTT broker, if any.
#username=""
# The password with which to authenticate to the MQTT broker, if any.
#password=""
# Whether to use TLS for the connection to the MQTT broker.
use_tls=false

[device."00:11:22:aa:bb:cc"]
name = "Barbecue thermometer"
probe_names = ["First probe", "Second probe"]
