[target.armv7-unknown-linux-gnueabihf]
image = "ghcr.io/qwandor/cross-dbus-debian-trixie-armv7:0.2.1-2"

[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/qwandor/cross-dbus-debian-trixie-aarch64:0.2.1-2"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/qwandor/cross-dbus-debian-trixie-x86_64:0.2.1-2"
