name: Lint

on:
  push:
    branches: [master]
  pull_request:

env:
  dbus-codegen-version: 0.9.1

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format Rust code
        run: cargo fmt
      - name: Check for differences
        run: git diff --exit-code
