name: Release

on:
  release:
    # A release, pre-release, or draft of a release is published.
    types: [published]

env:
  CARGO_TERM_COLOR: always
  cargo-deb-version: 1.28.0

jobs:
  push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        asset: ${{ github.event.release.assets }}
    steps:
      - name: Download package from release
        run: wget ${{ matrix.asset.browser_download_url }}
      - name: Parse filename
        id: parse_filename
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{ matrix.asset.name }}
          regex: "^[a-z0-9-]+_[0-9.-]+_([a-z0-9]+).deb$"
      - name: Upload deb package to Artifactory
        if: ${{ steps.parse_filename.outputs.match != '' }}
        run: >
          curl -H"Authorization: Bearer ${{ secrets.JFROG_TOKEN }}"
          -XPUT "https://homiers.jfrog.io/artifactory/homie-rs/pool/${{ matrix.asset.name }};deb.distribution=stable;deb.component=main;deb.architecture=${{ steps.parse_filename.outputs.group1 }}"
          -T "${{ matrix.asset.name }}"
